apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: foo-weather
  name: foo-weather
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/akinsanyaleke/foo-weather
      ref:
        branch: main